### PR TITLE
Add missing viewport details in lang spec pages

### PR DESCRIPTION
**Pull request by sm1990**
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9147

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Review by jclark — CHANGES_REQUESTED** [review]
Presentational stuff like this should go in spec.xsl not spec.html.

**Comment by sm1990** [comment]
> Presentational stuff like this should go in spec.xsl not spec.html.

I have updated the spec.xsl

**Review by jclark — CHANGES_REQUESTED** [review]
This is a tiny nit, but please move the added line one line down, so it's next to the other meta tag.

**Comment by sm1990** [comment]
> This is a tiny nit, but please move the added line one line down, so it's next to the other meta tag.

Sorry my bad. Committed the wrong file. Could you please review again.

**Review by jclark — COMMENTED** [review]
I didn't make myself clear in the previous comment. I just want the new `<meta>` tag, which you added before the `<title>` tag to be moved so that it is after the `<title>` tag, and next to the the `<meta charset` tag.

**Comment by sm1990** [comment]
> I didn't make myself clear in the previous comment. I just want the new `<meta>` tag, which you added before the `<title>` tag to be moved so that it is after the `<title>` tag, and next to the the `<meta charset` tag.

I have fixed the meta tag order. Could you please review again.

**Comment by sameerajayasoma** [comment]
@jclark, Could you please review this PR? Thanks

**Review by jclark — CHANGES_REQUESTED** [review]
This seems way too complicated. I would just add something like this to add the additional meta tag after the existing meta tag.

```
<xsl:template match="meta[@charset]">
  <xsl:copy-of select="."/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
</xsl:template>
```

**Review by sameerajayasoma — APPROVED** [review]

**Comment by anupama-pathirage** [comment]
@jclark Can you please review the changes?

**Pull request merged**
